// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuiqWDAP9ODTD1XybG2ENF257t1cGq2Xc',
    appId: '1:755105576724:web:e5cbe4eb0d2c437058b401',
    messagingSenderId: '755105576724',
    projectId: 'groovy-87ff7',
    authDomain: 'groovy-87ff7.firebaseapp.com',
    storageBucket: 'groovy-87ff7.appspot.com',
    measurementId: 'G-TQ33LFM0JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ3GOdcBZ8UidB6nI0oUNaTEX-s7A-tcM',
    appId: '1:755105576724:android:57932b8ad0bd289b58b401',
    messagingSenderId: '755105576724',
    projectId: 'groovy-87ff7',
    storageBucket: 'groovy-87ff7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVey3Tbf_g6wT0cX4anp4T66SmmBPN_2Y',
    appId: '1:755105576724:ios:12a9055bb51a1ca358b401',
    messagingSenderId: '755105576724',
    projectId: 'groovy-87ff7',
    storageBucket: 'groovy-87ff7.appspot.com',
    iosBundleId: 'com.example.groovy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVey3Tbf_g6wT0cX4anp4T66SmmBPN_2Y',
    appId: '1:755105576724:ios:12a9055bb51a1ca358b401',
    messagingSenderId: '755105576724',
    projectId: 'groovy-87ff7',
    storageBucket: 'groovy-87ff7.appspot.com',
    iosBundleId: 'com.example.groovy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuiqWDAP9ODTD1XybG2ENF257t1cGq2Xc',
    appId: '1:755105576724:web:879a14d0ee39b35a58b401',
    messagingSenderId: '755105576724',
    projectId: 'groovy-87ff7',
    authDomain: 'groovy-87ff7.firebaseapp.com',
    storageBucket: 'groovy-87ff7.appspot.com',
    measurementId: 'G-MS18RLEKWX',
  );
}
